name: CD - Deployment on Heroku

on:
  #  workflow_dispatch:
  #  push:
  #    branches:
  #      - develop
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: davidwrz
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}

      - name: Build Package Push with Maven
        run: mvn -ntp -B verify -Djib.to.image=davidwrz/quizapp:latest jib:dockerBuild

      - name: Push Image to Docker Hub
        run: docker push davidwrz/quizapp

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'quizappdavidwrz'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          docker_image_name: "davidwrz/quizapp"